### ISSUE TITLE
How to Use this with okta as IDP

### ISSUE THREAD

**Issue by sohan99** [Concerti-IO/openidconnect_flutter#1]
Can this be used with OKTA.

I tried the PKCE flow with okta
I get the below response for callback.html
"The authentication request has an invalid 'state' parameter."

**Comment by sohan99** [comment]
i got this working by adding state as additional parameter 
`"state": codeChallenge` 
InteractiveAuthorizationRequest._() in 
interactive_authorization_request.dart

**Comment by sohan99** [comment]
@jhancock4d  do you have any suggestions on this?

**Comment by jhancock4d** [comment]
OKTA is a standard IdP. All you have to do is use the sample with the .well-known configuration for Okta and then use the right type of login.

Here's One login's documentation which is consistent with the standard and shows that state is not required to be passed in this flow: https://developers.onelogin.com/openid-connect/api/authorization-code 

Here's Okta's instructions on the matter. Note that you don't need to pass state either unless you want to.  Don't follow the rest of their documentation here, they're doing string lookup on the entire query string and if they find "code=" anywhere they do different things which is a gross security issue: https://developer.okta.com/blog/2019/08/22/okta-authjs-pkce 

If you want to use Code Challenge you will use authorizeInteractive method which will do interactive code challenge login for you automatically without passing state. (I have tested this and it works correctly if you have your Okta IdP configured correctly. Note that you have to set it to PKCE for grantType "code" in the configuration. The handshake is handled automatically from there.) 

If you need to pass in any other parameters like state, simply add it to the additionalParameters on the InteractiveAuthorizationRequest in the authorizeInteractive method. You don't need to modify the source to add parameters.

This has been tested with Azure, Okta, Ping, Google, Facebook, and Twitter without issue.

You can modify the example code by putting in your values in the credentials.dart file and then running it on the platform of your choice. It gives you all of the possible ways that you can use openidconnect.

If you use authorizeInteractive on desktop devices (not including web) it will use device_code flow instead of code_challenge flow. It does this because those platforms don't yet have WebView nor secure authentication interfaces hooked up in flutter and I haven't had time/experience enough) to write the per platform code required to make it work. Android and iOS currently use WebView for code_challenge, but as soon as a bug is fixed in Flutter I will be switching those to use the OAuth library for Dart that works for those platforms.  

Web allows you to choose to either do a popup or a redirect loop. You must use a redirect loop if your request is not the result of a button click because of browser security issues. You'll be able to tell because you'll get a security error in the browser console if you can't use browser popup in that case.

Note that there is a (poorly documented) full client library that handles the entire process including refresh and recovery also included in this library that you can hook up to your app that will automatically handle everything for you.

If you're still having issues, please contact me directly, and provide me with a test endpoint with credentials on it, so that I can test against it and help you out/fix whatever it is that Okta doesn't like.
